[package]
name = "quinn-proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
thiserror = "1.0.21"

[dev-dependencies]
hex-literal = "0.4.0"