[package]
name = "scratch-quinn"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[dependencies]
tracing = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
